# Generated by Django 3.0.3 on 2020-02-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
